### ISSUE TITLE
Custom element doesn't exist

### ISSUE THREAD

**Issue by Smokey01966** [grinstantin/todoist-card#10]
**Before submitting a bug**
- [x] I updated to the latest card version available
- [x] I cleared the cache of my browser

**Describe the bug**
Card element started to show the error that the custom element Todoist card does not exist. I have cleared my cash on my main computer and the issue persists across multiple devices and browsers. I have tried both a reinstall through HACS as well as manual install.

**To Reproduce**
1. Install the custom card
2. Make a card (Have to use YAMAL because it does not show up as an option in the GUI)
3. Receive error (Configuration errors detected: Custom element not found: todoist-card)

**config**
```
rest_command:
  todoist:
    method: post
    url: "https://api.todoist.com/sync/v8/sync"
    payload: !secret todoist_api_payload
    content_type: "application/x-www-form-urlencoded"

sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
  #todoist
  - platform: rest
    name: To-do List
    method: GET
    resource: "https://api.todoist.com/sync/v8/projects/get_data"
    params:
      token: !secret todoist_api_token
      project_id: 2253650771
    value_template: "{{value_json['project']['id']}}"
    json_attributes:
      - items
    scan_interval: 30
  - platform: rest
    name: Shopping List
    method: GET
    resource: "https://api.todoist.com/sync/v8/projects/get_data"
    params:
      token: !secret todoist_api_token
      project_id: 2253650772
    value_template: "{{value_json['project']['id']}}"
    json_attributes:
      - items
    scan_interval: 30
```

**Versions:**
 - Card: [v1.0.8]
 - HomeAssistant: [2022.6.4]
 - Browser:
 --Home assistant app 2022.3.0-full
--Edge 102.0.1245.33
--Edge mobile 101.0.1210.53
-- Chromium 92.9.4515.98

**Additional context**
Started to happen after HA 2022.6.0 update
