### ISSUE TITLE
[BUG] I can't add new items after update to the last version 

### ISSUE THREAD

**Issue by MiguelCosta** [grinstantin/todoist-card#14]
**Before submitting a bug**
- [X] I updated to the latest card version available
- [X] I cleared the cache of my browser

**Describe the bug**
We can't add items using todoist-card

**To Reproduce**
1. Go to todoist card
2. Add new item using and press enter
3. Errors

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:421
First occurred: 14:17:53 (15 occurrences)
Last logged: 14:33:03

Template variable warning: 'commands' is undefined when rendering 'token=*************&commands={{commands}}'
```
```
Logger: homeassistant.components.rest_command
Source: components/rest_command/__init__.py:137
Integration: RESTful Command (documentation, issues)
First occurred: 14:17:53 (15 occurrences)
Last logged: 14:33:03

Error. Url: https://api.todoist.com/sync/v9/sync. Status code 400. Payload: b'token=*************&commands='
```

**Expected behavior**
Add the new item

**Screenshots**

![todoist](https://user-images.githubusercontent.com/645482/186171159-3fea7b7e-f425-49ad-bb42-ff2726653ee5.gif)

**Versions:**
 - Card: 1.1.0
 - HomeAssistant: 2022.8.6
 - Browser: Google Chrome 107.0.5256.0

**Additional context**
This issue started after update todoist-card to the last version

configuration.yaml

```
sensor:
  - platform: rest
    name: Lista de compras
    method: GET
    resource: "https://api.todoist.com/sync/v9/projects/get_data"
    params:
      token: !secret todoist_api_token
      project_id: *******
    value_template: "{{ value_json['project']['id'] }}"
    json_attributes:
      - project
      - items
    scan_interval: 30
  - platform: rest
    name: Lista de tarefas
    method: GET
    resource: "https://api.todoist.com/sync/v9/projects/get_data"
    params:
      token: !secret todoist_api_token
      project_id: ********
    value_template: "{{ value_json['project']['id'] }}"
    json_attributes:
      - project
      - items
    scan_interval: 30

rest_command:
  todoist:
    method: post
    url: "https://api.todoist.com/sync/v9/{{ url }}"
    payload: !secret todoist_api_payload
    content_type: "application/x-www-form-urlencoded"
```
