### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by chicknlil** [grinstantin/todoist-card#18]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem, but I'm not able to implement it as I hoped.  It appears that you can only use this card to show one project.

**Describe the solution you'd like**
I'm looking to have multiple instances of this card running in different views, each reflecting the corresponding Todoist project list.

**Describe alternatives you've considered**
I tried editing the yaml in a way that I thought would allow me to create multiple instances, but I'm too much of a newb and I failed miserably.

**Additional context**
![Upstairs-Hallway-Todoist](https://user-images.githubusercontent.com/100124187/194732006-c51e311b-6258-49bd-a23f-43264c7b7764.png)

**Comment by grinstantin** [comment]
Hi! You can easily create multiple `sensors` for your Todoist projects and then use them in different views.
```
sensor:
  - platform: rest
    name: First To-do List
    method: GET
    resource: 'https://api.todoist.com/sync/v9/projects/get_data'
    params:
      token: !secret todoist_api_token
      project_id: FIRST_TODOIST_PROJECT_ID
    value_template: '{{ value_json[''project''][''id''] }}'
    json_attributes:
      - project
      - items
    scan_interval: 30
  - platform: rest
    name: Second To-do List
    method: GET
    resource: 'https://api.todoist.com/sync/v9/projects/get_data'
    params:
      token: !secret todoist_api_token
      project_id: SECOND_TODOIST_PROJECT_ID
    value_template: '{{ value_json[''project''][''id''] }}'
    json_attributes:
      - project
      - items
    scan_interval: 30
```
Just replace `FIRST_TODOIST_PROJECT_ID` and `SECOND_TODOIST_PROJECT_ID` with IDs of your projects.
