### ISSUE TITLE
[BUG] Can't seem to delete or make new things from the card.

### ISSUE THREAD

**Issue by six-shooter** [grinstantin/todoist-card#22]
Hello there, 

My card does populate, but I can't seem to delete or add items to the list from the HA-card.

Here is the code I used for the card:

```
type: custom:todoist-card
entity: sensor.to_do_list
use_quick_add: true
```

And here is the config: 

```
###### TODOIST #######
  - platform: rest
    name: To-do List
    method: GET
    resource: 'https://api.todoist.com/sync/v8/projects/get_data'
    params:
      token: !secret todoist_api_token
      project_id: 2294544217
    value_template: '{{value_json[''project''][''id'']}}'
    json_attributes:
      - items
    scan_interval: 30
    
rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v8/sync'
    payload: !secret todoist_api_payload
    content_type: 'application/x-www-form-urlencoded'
##### TODOIST END #########
```
