### ISSUE TITLE
[BUG] Card stop working - Requests are returning 403

### ISSUE THREAD

**Issue by MiguelCosta** [grinstantin/todoist-card#25]
**Before submitting a bug**
- [X] I updated to the latest card version available
- [X] I cleared the cache of my browser

**Describe the bug**
I am using the cards a few months ago and the card stop working without any change from my side.
The requests are return 403 but I already confirm and the token is correct.

Can you help?

The token is correct
**To Reproduce**
1. Go to the card
2. Add a new item
3. Check the logs

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/645482/209362513-413786e2-0644-4af6-ae4f-fd697a68a2f9.png)

**Versions:**
 - Card: 1.1.2
 - HomeAssistant: 2022.12.8
 - Browser: Google Chrome 111.0.5492.0 

**Additional context**

configuration.yaml

```
sensor:
  - platform: rest
    name: Lista de compras
    method: GET
    resource: "https://api.todoist.com/sync/v9/projects/get_data"
    params:
      token: !secret todoist_api_token
      project_id: **********
    value_template: "{{ value_json['project']['id'] }}"
    json_attributes:
      - project
      - items
    scan_interval: 30
  - platform: rest
    name: Lista de tarefas
    method: GET
    resource: "https://api.todoist.com/sync/v9/projects/get_data"
    params:
      token: !secret todoist_api_token
      project_id: **********
    value_template: "{{ value_json['project']['id'] }}"
    json_attributes:
      - project
      - items
    scan_interval: 30
```

secrets.yaml

```
todoist_api_token: ****************************************
todoist_api_payload: token=***********************************&{{ payload }}
```

**Comment by Some1Elsewhere** [comment]
I can second that behavior.

`Logger: homeassistant.components.rest_command
Source: components/rest_command/__init__.py:137
Integration: RESTful Command ([documentation](https://www.home-assistant.io/integrations/rest_command), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+rest_command%22))
First occurred: 00:13:26 (5 occurrences)
Last logged: 17:44:30

    Error. Url: https://api.todoist.com/sync/v9/sync. Status code 403. Payload: b'token=bccc7cdd3f0892ac31cda643c15963db42b63754&commands=[{"type":"item_add","temp_id":"54-1671750806523-523","uuid":"54-1671750806523-523","args":{"project_id":"unknown","content":"test"}}]'
    Error. Url: https://api.todoist.com/sync/v9/sync. Status code 403. Payload: b'token=bccc7cdd3f0892ac31cda643c15963db42b63754&commands=[{"type":"item_add","temp_id":"37-1671750820739-739","uuid":"37-1671750820739-739","args":{"project_id":"unknown","content":"test"}}]'
    Error. Url: https://api.todoist.com/sync/v9/sync. Status code 403. Payload: b'token=bccc7cdd3f0892ac31cda643c15963db42b63754&commands=[{"type":"item_add","temp_id":"48-1671752196463-463","uuid":"48-1671752196463-463","args":{"project_id":"unknown","content":"jfjrjrjr"}}]'
    Error. Url: https://api.todoist.com/sync/v9/sync. Status code 403. Payload: b'token=bccc7cdd3f0892ac31cda643c15963db42b63754&commands=[{"type":"item_add","temp_id":"63-1671813868481-481","uuid":"63-1671813868481-481","args":{"project_id":"unknown","content":"test"}}]'
    Error. Url: https://api.todoist.com/sync/v9/sync. Status code 403. Payload: b'token=bccc7cdd3f0892ac31cda643c15963db42b63754&commands=[{"type":"item_add","temp_id":"68-1671813870206-206","uuid":"68-1671813870206-206","args":{"project_id":"unknown","content":"test"}}]'`

**Comment by grinstantin** [comment]
Hi. Please, check the state of your `sensor`. Does it contain your `project_id`?

**Comment by MiguelCosta** [comment]
> Hi. Please, check the state of your `sensor`. Does it contain your `project_id`?

What sensor? 🤔

My configuration.yaml contains the project_id...

**Comment by MiguelCosta** [comment]
![Screenshot_20221223-225329](https://user-images.githubusercontent.com/645482/209411657-b779bb1f-dc38-485d-9c0e-a29563b59496.png)

**Comment by MiguelCosta** [comment]
With the attributes:

![Screenshot_20221223-230008](https://user-images.githubusercontent.com/645482/209412015-df6af819-c8e2-450f-ac62-107869a0e578.png)

**Comment by grinstantin** [comment]
Please, search logs for any errors, related to `v9/projects/get_data` endpoint - I can't run my local server with HA instance on it now :(

**Comment by bernikr** [comment]
As elaborated in my pull request, there was a change in how the api handles authentication and you have to change your config and secrets file:

Config:
```yaml
sensor:
  - platform: rest
    name: To-do List
    method: GET
    resource: 'https://api.todoist.com/sync/v9/projects/get_data'
    params:
      project_id: TODOIST_PROJECT_ID
    headers:
      Authorization: !secret todoist_api_token
    value_template: '{{ value_json[''project''][''id''] }}'
    json_attributes:
      - project
      - items
    scan_interval: 30

rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v9/{{ url }}'
    payload: '{{ payload }}'
    headers:
      Authorization: !secret todoist_api_token
    content_type: 'application/x-www-form-urlencoded'
```
Secrets:
```yaml
todoist_api_token: 'Bearer TODOIST_API_TOKEN'
```
