### ISSUE TITLE
[BUG] Error communicating with API: 401 Client Error: Unauthorized for url: https://api.todoist.com/rest/v2/tasks

### ISSUE THREAD

**Issue by asd343** [grinstantin/todoist-card#52]
Installed from HACS.

Added to configuration.yaml and secrets.yaml - double and triple checked values.

I get this error.

I tried making a manual GET req to my API to verify my key/token, and it worked (I got a 200 response, with the tasks on my list)

![image](https://github.com/user-attachments/assets/adb8284e-6b20-496f-b5a8-e1cd45ed4ddb)

configuration.yaml
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: rest
    name: To-do List
    method: GET
    resource: 'https://api.todoist.com/sync/v9/projects/get_data'
    params:
      project_id: 2245062669
    headers:
      Authorization: !secret todoist_api_token
    value_template: '{{ value_json[''project''][''id''] }}'
    json_attributes:
      - project
      - items
    scan_interval: 30

rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v9/{{ url }}'
    payload: '{{ payload }}'
    headers:
      Authorization: !secret todoist_api_token
    content_type: 'application/x-www-form-urlencoded'
```

secrets.yaml

```
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
some_password: welcome

todoist_api_token: 'Bearer MY-KEY-TESTED-AND-VERIFIED'
```
