### ISSUE TITLE
[FEATURE REQUEST] Possible to show a filter instead of a project?

### ISSUE THREAD

**Issue by asd343** [grinstantin/todoist-card#53]
Is it possible to get a list of tasks from a filter, instead of a project? It would give alot more flexibility in what tasks to show.

**Comment by pgorod** [comment]
@asd343 you may want to look at the additional filtering options in my fork of this card (although they don't have strictly what you ask for, you might find ways to filter locally, to your satisfaction)

https://github.com/pgorod/power-todoist-card/

I also just asked ChatGPT about changing the sensor in Home Assistant to get just items for a filter, instead of all of them. If this works then we would get filter functionality in both my card and this one here, without changin any code 🚀 

```
- name: ToDoist Filtered Tasks
  platform: rest
  method: POST
  resource: "https://api.todoist.com/sync/v9/sync"
  headers:
    Authorization: !secret todoist_api_token
    Content-Type: application/x-www-form-urlencoded
  payload: "sync_token=*&resource_types=[\"items\"]&filter=today"
  value_template: "{{ value_json['items'] | length }}"
  json_attributes:
    - project
    - items
    - sections
    - project_notes
  scan_interval: 60
```
I haven't tried it...
