### ISSUE TITLE
[BUG] Card Does not show on Dashboard

### ISSUE THREAD

**Issue by neek0la** [grinstantin/todoist-card#8]
**Before submitting a bug**
- [x] I updated to the latest card version available
- [x] I cleared the cache of my browser

**Describe the bug**
After saving the example card shown, the card does not appear on the dashboard. 
The code for the card is in the dashboard but nothing appears.
When entering the code, todoist visual editor shows the card

**Comment by grinstantin** [comment]
Are there any errors in the developer console or in the HA logs? Does the HA have a `sensor` that stores data about your list?

**Comment by neek0la** [comment]
There is nothing in the logs relating to todoist.

You are correct. There is no sensor relating to the list.
I have double checked the API code and the token so not sure where the problem is

**Comment by grinstantin** [comment]
Paste here your configuration, please (without sensitive information, of course).

**Comment by neek0la** [comment]
Let me know what you think

Configuration.yaml
```
sensor:
  - platform: rest
    name: To-do List
    method: GET
    resource: 'https://api.todoist.com/sync/v8/projects/get_data'
    params:
      token: !secret todoist_api_token
      project_id: https://todoist.com/app/project/SENSITIVE
    value_template: '{{value_json[''project''][''id'']}}'
    json_attributes:
      - items
    scan_interval: 30

rest_command:
  todoist:
    method: post
    url: 'https://api.todoist.com/sync/v8/sync'
    payload: !secret todoist_api_payload
    content_type: 'application/x-www-form-urlencoded'
```

Secrets.yaml
```
todoist_api_token: SENSITIVE
todoist_api_payload: token=SENSITIVE&commands={{commands}}
```
